engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: false
  bundler-audit:
    enabled: true
ratings:
  paths:
    - "app/**"
    - Gemfile.lock
exclude_paths:
  - "vendor/**"
